left_gripper:
  - 0.999
  - 0.999
  - 0.999
  - 0.999
  - 0.999
  - 0.999

right_gripper:
  - 0.999
  - 0.999
  - 0.999
  - 0.999
  - 0.999
  - 0.999

# left_gripper:
#   - 0.3
#   - 0.3
#   - 0.3
#   - 0.3
#   - 0.001
#   - 0.3

# right_gripper:
#   - 0.3
#   - 0.3
#   - 0.3
#   - 0.3
#   - 0.001
#   - 0.3