
(cl:in-package :asdf)

(defsystem "llm_msgs-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "get_angle_act" :depends-on ("_package_get_angle_act"))
    (:file "_package_get_angle_act" :depends-on ("_package"))
    (:file "get_error" :depends-on ("_package_get_error"))
    (:file "_package_get_error" :depends-on ("_package"))
    (:file "get_force_act" :depends-on ("_package_get_force_act"))
    (:file "_package_get_force_act" :depends-on ("_package"))
    (:file "get_status" :depends-on ("_package_get_status"))
    (:file "_package_get_status" :depends-on ("_package"))
    (:file "joint_set_zero" :depends-on ("_package_joint_set_zero"))
    (:file "_package_joint_set_zero" :depends-on ("_package"))
    (:file "set_angle" :depends-on ("_package_set_angle"))
    (:file "_package_set_angle" :depends-on ("_package"))
    (:file "set_angle_flexible" :depends-on ("_package_set_angle_flexible"))
    (:file "_package_set_angle_flexible" :depends-on ("_package"))
    (:file "set_clear_error" :depends-on ("_package_set_clear_error"))
    (:file "_package_set_clear_error" :depends-on ("_package"))
    (:file "set_force" :depends-on ("_package_set_force"))
    (:file "_package_set_force" :depends-on ("_package"))
    (:file "set_speed" :depends-on ("_package_set_speed"))
    (:file "_package_set_speed" :depends-on ("_package"))
  ))