arm_controllers:

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 400  # in Hz

    jointZ_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: waist_Z_joint
      pid: {p: 100.0, i: 0.0, d: 10}  
    joint0x_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: waist_roll_joint
      pid: {p: 10.0, i: 0.01, d: 2}   
    joint0y_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: waist_pitch_joint
      pid: {p: 10.0, i: 0.01, d: 2}  
    joint0z_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: waist_yaw_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint1_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: shoulder_pitch_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint2_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: shoulder_roll_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint3_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: shoulder_yaw_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint4_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: elbow_pitch_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint5_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: elbow_yaw_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint6_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wrist_pitch_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint7_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wrist_roll_l_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint8_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: shoulder_pitch_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint9_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: shoulder_roll_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint10_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: shoulder_yaw_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint11_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: elbow_pitch_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint12_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: elbow_yaw_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint13_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wrist_pitch_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    joint14_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wrist_roll_r_joint
      pid: {p: 10.0, i: 0.01, d: 2}

    # joint0_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: waist_yaw_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}
    # joint1_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: shoulder_pitch_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint2_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: shoulder_roll_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint3_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: shoulder_yaw_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint4_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: elbow_pitch_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint5_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: elbow_yaw_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint6_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: wrist_pitch_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint7_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: wrist_roll_l_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}



    # joint8_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: shoulder_pitch_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint9_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: shoulder_roll_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint10_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: shoulder_yaw_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint11_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: elbow_pitch_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint12_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: elbow_yaw_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint13_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: wrist_pitch_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}

    # joint14_effort_controller:
    #   type: effort_controllers/JointEffortController
    #   joint: wrist_roll_r_joint
    #   pid: {p:  1.0, i: 0.01, d: 2}