controller:
  lambda_gain: 11.5
  eta_gain: 0.15

impedance:
  Mass: 
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
  Damping: 
    - 8.0
    - 8.0  
    - 8.0
    - 1.0
    - 1.0
    - 1.0
  Stiff:
    - 100.0
    - 50.0  
    - 50.0  
    - 2.0  
    - 2.0  
    - 2.0  
  sensor_used: false
  control_mode: 1