controller:
  lambda_gain: 11.5
  eta_gain: 0.15

impedance:
  Mass: 
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
    - 1.0  
  Damping: 
    - 1.0
    - 1.0
    - 1.0  
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  Stiff:
    - 5.0  
    - 5.0  
    - 15.0  
    - 15.0  
    - 5.0  
    - 15.0  
    - 15.0  
  sensor_used: false
  control_mode: 0