// Generated by gencpp from file llm_msgs/get_statusResponse.msg
// DO NOT EDIT!


#ifndef LLM_MSGS_MESSAGE_GET_STATUSRESPONSE_H
#define LLM_MSGS_MESSAGE_GET_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace llm_msgs
{
template <class ContainerAllocator>
struct get_statusResponse_
{
  typedef get_statusResponse_<ContainerAllocator> Type;

  get_statusResponse_()
    : statusvalue()  {
      statusvalue.assign(0);
  }
  get_statusResponse_(const ContainerAllocator& _alloc)
    : statusvalue()  {
  (void)_alloc;
      statusvalue.assign(0);
  }



   typedef boost::array<uint32_t, 6>  _statusvalue_type;
  _statusvalue_type statusvalue;





  typedef boost::shared_ptr< ::llm_msgs::get_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm_msgs::get_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_statusResponse_

typedef ::llm_msgs::get_statusResponse_<std::allocator<void> > get_statusResponse;

typedef boost::shared_ptr< ::llm_msgs::get_statusResponse > get_statusResponsePtr;
typedef boost::shared_ptr< ::llm_msgs::get_statusResponse const> get_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm_msgs::get_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm_msgs::get_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm_msgs::get_statusResponse_<ContainerAllocator1> & lhs, const ::llm_msgs::get_statusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.statusvalue == rhs.statusvalue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm_msgs::get_statusResponse_<ContainerAllocator1> & lhs, const ::llm_msgs::get_statusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm_msgs::get_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_msgs::get_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_msgs::get_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f7cdabc561edd46a5ab52db3c6d6e89";
  }

  static const char* value(const ::llm_msgs::get_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f7cdabc561edd46ULL;
  static const uint64_t static_value2 = 0xa5ab52db3c6d6e89ULL;
};

template<class ContainerAllocator>
struct DataType< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm_msgs/get_statusResponse";
  }

  static const char* value(const ::llm_msgs::get_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[6] statusvalue\n"
;
  }

  static const char* value(const ::llm_msgs::get_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusvalue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm_msgs::get_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm_msgs::get_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "statusvalue[]" << std::endl;
    for (size_t i = 0; i < v.statusvalue.size(); ++i)
    {
      s << indent << "  statusvalue[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.statusvalue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_MSGS_MESSAGE_GET_STATUSRESPONSE_H
