// Generated by gencpp from file llm_msgs/robot_state.msg
// DO NOT EDIT!


#ifndef LLM_MSGS_MESSAGE_ROBOT_STATE_H
#define LLM_MSGS_MESSAGE_ROBOT_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace llm_msgs
{
template <class ContainerAllocator>
struct robot_state_
{
  typedef robot_state_<ContainerAllocator> Type;

  robot_state_()
    : header()
    , head_pose()  {
    }
  robot_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , head_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _head_pose_type;
  _head_pose_type head_pose;





  typedef boost::shared_ptr< ::llm_msgs::robot_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm_msgs::robot_state_<ContainerAllocator> const> ConstPtr;

}; // struct robot_state_

typedef ::llm_msgs::robot_state_<std::allocator<void> > robot_state;

typedef boost::shared_ptr< ::llm_msgs::robot_state > robot_statePtr;
typedef boost::shared_ptr< ::llm_msgs::robot_state const> robot_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm_msgs::robot_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm_msgs::robot_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm_msgs::robot_state_<ContainerAllocator1> & lhs, const ::llm_msgs::robot_state_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.head_pose == rhs.head_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm_msgs::robot_state_<ContainerAllocator1> & lhs, const ::llm_msgs::robot_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm_msgs::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm_msgs::robot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_msgs::robot_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_msgs::robot_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_msgs::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_msgs::robot_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm_msgs::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "138e1f0b512da903c8d31155a12f0ec5";
  }

  static const char* value(const ::llm_msgs::robot_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x138e1f0b512da903ULL;
  static const uint64_t static_value2 = 0xc8d31155a12f0ec5ULL;
};

template<class ContainerAllocator>
struct DataType< ::llm_msgs::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm_msgs/robot_state";
  }

  static const char* value(const ::llm_msgs::robot_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm_msgs::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# 头部姿态数据\n"
"float64[] head_pose #X, Y, Z, R, P, Y\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::llm_msgs::robot_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm_msgs::robot_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.head_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm_msgs::robot_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm_msgs::robot_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "head_pose[]" << std::endl;
    for (size_t i = 0; i < v.head_pose.size(); ++i)
    {
      s << indent << "  head_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.head_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_MSGS_MESSAGE_ROBOT_STATE_H
