// Generated by gencpp from file llm_msgs/set_speedResponse.msg
// DO NOT EDIT!


#ifndef LLM_MSGS_MESSAGE_SET_SPEEDRESPONSE_H
#define LLM_MSGS_MESSAGE_SET_SPEEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace llm_msgs
{
template <class ContainerAllocator>
struct set_speedResponse_
{
  typedef set_speedResponse_<ContainerAllocator> Type;

  set_speedResponse_()
    : speed_accepted(false)  {
    }
  set_speedResponse_(const ContainerAllocator& _alloc)
    : speed_accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _speed_accepted_type;
  _speed_accepted_type speed_accepted;





  typedef boost::shared_ptr< ::llm_msgs::set_speedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm_msgs::set_speedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_speedResponse_

typedef ::llm_msgs::set_speedResponse_<std::allocator<void> > set_speedResponse;

typedef boost::shared_ptr< ::llm_msgs::set_speedResponse > set_speedResponsePtr;
typedef boost::shared_ptr< ::llm_msgs::set_speedResponse const> set_speedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm_msgs::set_speedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm_msgs::set_speedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm_msgs::set_speedResponse_<ContainerAllocator1> & lhs, const ::llm_msgs::set_speedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.speed_accepted == rhs.speed_accepted;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm_msgs::set_speedResponse_<ContainerAllocator1> & lhs, const ::llm_msgs::set_speedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm_msgs::set_speedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_msgs::set_speedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_msgs::set_speedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bb3ff7624b31e52edd1d0b2bbbae418";
  }

  static const char* value(const ::llm_msgs::set_speedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bb3ff7624b31e52ULL;
  static const uint64_t static_value2 = 0xedd1d0b2bbbae418ULL;
};

template<class ContainerAllocator>
struct DataType< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm_msgs/set_speedResponse";
  }

  static const char* value(const ::llm_msgs::set_speedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool speed_accepted\n"
"\n"
;
  }

  static const char* value(const ::llm_msgs::set_speedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed_accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_speedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm_msgs::set_speedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm_msgs::set_speedResponse_<ContainerAllocator>& v)
  {
    s << indent << "speed_accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_MSGS_MESSAGE_SET_SPEEDRESPONSE_H
