// Generated by gencpp from file llm_msgs/set_angle.msg
// DO NOT EDIT!


#ifndef LLM_MSGS_MESSAGE_SET_ANGLE_H
#define LLM_MSGS_MESSAGE_SET_ANGLE_H

#include <ros/service_traits.h>


#include <llm_msgs/set_angleRequest.h>
#include <llm_msgs/set_angleResponse.h>


namespace llm_msgs
{

struct set_angle
{

typedef set_angleRequest Request;
typedef set_angleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_angle
} // namespace llm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::llm_msgs::set_angle > {
  static const char* value()
  {
    return "3f54cd874965b27feb654abae7abbdcb";
  }

  static const char* value(const ::llm_msgs::set_angle&) { return value(); }
};

template<>
struct DataType< ::llm_msgs::set_angle > {
  static const char* value()
  {
    return "llm_msgs/set_angle";
  }

  static const char* value(const ::llm_msgs::set_angle&) { return value(); }
};


// service_traits::MD5Sum< ::llm_msgs::set_angleRequest> should match
// service_traits::MD5Sum< ::llm_msgs::set_angle >
template<>
struct MD5Sum< ::llm_msgs::set_angleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::llm_msgs::set_angle >::value();
  }
  static const char* value(const ::llm_msgs::set_angleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_msgs::set_angleRequest> should match
// service_traits::DataType< ::llm_msgs::set_angle >
template<>
struct DataType< ::llm_msgs::set_angleRequest>
{
  static const char* value()
  {
    return DataType< ::llm_msgs::set_angle >::value();
  }
  static const char* value(const ::llm_msgs::set_angleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::llm_msgs::set_angleResponse> should match
// service_traits::MD5Sum< ::llm_msgs::set_angle >
template<>
struct MD5Sum< ::llm_msgs::set_angleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::llm_msgs::set_angle >::value();
  }
  static const char* value(const ::llm_msgs::set_angleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_msgs::set_angleResponse> should match
// service_traits::DataType< ::llm_msgs::set_angle >
template<>
struct DataType< ::llm_msgs::set_angleResponse>
{
  static const char* value()
  {
    return DataType< ::llm_msgs::set_angle >::value();
  }
  static const char* value(const ::llm_msgs::set_angleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLM_MSGS_MESSAGE_SET_ANGLE_H
