// Generated by gencpp from file llm_msgs/set_speed.msg
// DO NOT EDIT!


#ifndef LLM_MSGS_MESSAGE_SET_SPEED_H
#define LLM_MSGS_MESSAGE_SET_SPEED_H

#include <ros/service_traits.h>


#include <llm_msgs/set_speedRequest.h>
#include <llm_msgs/set_speedResponse.h>


namespace llm_msgs
{

struct set_speed
{

typedef set_speedRequest Request;
typedef set_speedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_speed
} // namespace llm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::llm_msgs::set_speed > {
  static const char* value()
  {
    return "4d1d00d67ce0ba0765e4ad67b563d391";
  }

  static const char* value(const ::llm_msgs::set_speed&) { return value(); }
};

template<>
struct DataType< ::llm_msgs::set_speed > {
  static const char* value()
  {
    return "llm_msgs/set_speed";
  }

  static const char* value(const ::llm_msgs::set_speed&) { return value(); }
};


// service_traits::MD5Sum< ::llm_msgs::set_speedRequest> should match
// service_traits::MD5Sum< ::llm_msgs::set_speed >
template<>
struct MD5Sum< ::llm_msgs::set_speedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::llm_msgs::set_speed >::value();
  }
  static const char* value(const ::llm_msgs::set_speedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_msgs::set_speedRequest> should match
// service_traits::DataType< ::llm_msgs::set_speed >
template<>
struct DataType< ::llm_msgs::set_speedRequest>
{
  static const char* value()
  {
    return DataType< ::llm_msgs::set_speed >::value();
  }
  static const char* value(const ::llm_msgs::set_speedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::llm_msgs::set_speedResponse> should match
// service_traits::MD5Sum< ::llm_msgs::set_speed >
template<>
struct MD5Sum< ::llm_msgs::set_speedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::llm_msgs::set_speed >::value();
  }
  static const char* value(const ::llm_msgs::set_speedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_msgs::set_speedResponse> should match
// service_traits::DataType< ::llm_msgs::set_speed >
template<>
struct DataType< ::llm_msgs::set_speedResponse>
{
  static const char* value()
  {
    return DataType< ::llm_msgs::set_speed >::value();
  }
  static const char* value(const ::llm_msgs::set_speedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLM_MSGS_MESSAGE_SET_SPEED_H
