(cl:in-package llm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HAND_MOVE_ENABLE-VAL
          HAND_MOVE_ENABLE
          HAND_SIDE-VAL
          HAND_SIDE
          HAND_RESET-VAL
          HAND_RESET
          POSE_REQ-VAL
          POSE_REQ
          HEAD_MOVE_ENABLE-VAL
          HEAD_MOVE_ENABLE
          RPY-VAL
          RPY
          GRIPPER_MOVE_ENABLE-VAL
          GRIPPER_MOVE_ENABLE
          GRIPPER_SIDE-VAL
          GRIPPER_SIDE
          FINGER_STATUS-VAL
          FINGER_STATUS
          LITTLE_FINGER-VAL
          LITTLE_FINGER
          RING_FINGER-VAL
          RING_FINGER
          MIDDLE_FINGER-VAL
          MIDDLE_FINGER
          INDEX_FINGER-VAL
          INDEX_FINGER
          THUMB_BENDING-VAL
          THUMB_BENDING
          THUMB_ROTATING-VAL
          THUMB_ROTATING
          WAIST_ENABLE-VAL
          WAIST_ENABLE
          WAIST_ROTATE_ANG-VAL
          WAIST_ROTATE_ANG
))